name: Wild
main: SkyLightMCPE\Main
version: 1.0.0-B1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: [VMPE Development Team]
website: https://github.com/SkyLightMCPE
commands:
 wild:
  usage: /wild 
  description: Teleports you in a random place!
  permission: wild.command
  default: true
